### ISSUE TITLE
Bug in 2.81a

### ISSUE THREAD

**Issue by Hard3D** [Noizirom/Pino_kio-Ragdoll-Engine#1]
Hello! I click on button Pino_Kio Ragdoll and there is an error:

``
Traceback (most recent call last):
  File "/Text", line 533, in execute
  File "/Text", line 456, in Ragdoll
  File "/Text", line 341, in ragdoll_obj
  File "/Text", line 293, in add_capsule
  File "/Text", line 287, in obj_new
  File "/Text", line 282, in obj_mesh
KeyError: 'bpy_prop_collection[key]: key "Collection" not found 
location: <unknown location>:-1``

I tested on MB Lab rig.

**Comment by Noizirom** [comment]
The engine hasn't been updated for blender 2.81. I've been busy with the
hair engine.  I will look into it over the holidays.

**Comment by Noizirom** [comment]
I've just updated the engine. its ready for testing. I plan to add an engine for the fingers, but I'm experiencing performance issues with my pc. Please be patient.
